---
title: "Functional Enrichment Analysis Plots - MVP"
author: "Katie Hooker"
date: "2025-02-17"
output: html_document
---


This script is for plotting the outputs of the functional enrichment analysis run on the 97 selected MVP phenotypes.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggplot2))
library(stringr)
library(DT)

```

# Plotting function
```{r}
enrichment_plot <- function(data, group, xlim=NULL){
  
  group = sym(group)
  p <- ggplot(data, aes(x = Enrichment, y = !!group))+
    geom_point() +
    xlab("Enrichment") +
    geom_errorbarh(aes(xmin=Enrichment-CI_width, xmax=Enrichment+CI_width), height=.2) +
    facet_wrap(Trait_label~.,ncol = 1) +
    theme_bw()  +
    geom_vline(xintercept = 1,linetype="dotted", colour = "red") +
    theme(axis.ticks = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(colour = "black"),
      axis.text = element_text(size = 8, colour = "black"),
      axis.title = element_text(face="bold",size = 12),
      strip.text = element_text(face="bold",size = 10),
      panel.spacing.x = unit(0.6,units = "cm"),
      axis.title.y = element_blank(),
      legend.position = "none",
      plot.title = element_text(hjust = 0.5))
  
  if(!is.null(xlim)){
    p <- p + coord_cartesian(xlim = xlim)
  }
  print(p)

}
```

# Compiling all trait results
```{r}
output_path <- "/dartfs/rc/lab/S/Szhao/katieh/organoid-rotation/outputs/MVP/"

# Reading in trait abbreviations and their corresponding trait names
pheno_list <- read.csv("/dartfs/rc/lab/S/Szhao/katieh/organoid-rotation/data/MVP_pheno_list.csv")

# Fixing traits that are not unique after shortening
pheno_list[pheno_list$Description == "Irritable Bowel Syndrome (IBS)",]$Description <- "Irritable Bowel Syndrome survey result"
pheno_list[pheno_list$Description == "glucose (finger stick, mean, inv-norm transformed)",]$Description <- "Glucose finger stick result"

pheno_list <- pheno_list %>% 
  mutate(Short_desc = str_trim(gsub("\\(.*?\\)", "", Description))) %>% 
  mutate(Short_desc = str_to_sentence(Short_desc)) %>% 
  mutate(Short_desc = gsub("(?i)Gerd", "GERD", Short_desc)) %>% 
  mutate(Short_desc = gsub("(?i)nos", "NOS", Short_desc))

odd_rows <- seq_len(nrow(pheno_list)) %% 2
pheno_list_unique <- pheno_list[odd_rows==1,]
  
pheno_list_unique$N_desc <- NA

for (trait in pheno_list_unique$Trait){
  if (pheno_list_unique[pheno_list_unique$Trait == trait,]$Category == "Labs") {
    N_string = paste0("N total = ", pheno_list_unique[pheno_list_unique$Trait == trait,]$num_samples.EUR)
  } else {
    N_string = paste0("N cases = ", pheno_list_unique[pheno_list_unique$Trait == trait,]$num_cases.EUR, ", N controls = ", pheno_list_unique[pheno_list_unique$Trait == trait,]$num_controls.EUR)
  }
  pheno_list_unique[pheno_list_unique$Trait == trait,]$N_desc <- N_string
}

pheno_list_unique <- pheno_list_unique %>% mutate(Short_desc = paste0(Short_desc, " (", N_desc, ")"))
traits <- pheno_list_unique$Trait
traitslab <- pheno_list_unique$Short_desc

all_traits <- NULL 
for (i in 1:length(traits)){
  efile1 <- read.table(paste0(output_path, sprintf("results/%s_enrichment.results", traits[i])),
                       header=T)
  enrich <- efile1[1:4,c(1,5,6,7)]
  enrich$CI_width <- 1.96*enrich$Enrichment_std_error
  enrich$Trait <- traits[i]
  enrich$Trait_label <- traitslab[i]

  if(is.null(all_traits)){
    all_traits <- enrich
  } else{
    all_traits <- rbind(all_traits, enrich)
  }
}
```

# Plot all traits, four at a time
```{r}
for (i in seq(1, nrow(all_traits), 16)){
  enrichment_plot(all_traits[i:(i+15),], group="Category", xlim=c(-120,120))
}
# Last trait
enrichment_plot(all_traits[385:388,], group="Category", xlim=c(-120,120))

```
# Plot traits of interest
```{r}
all_traits_sub <- all_traits %>% subset(Trait_label == "Hemoglobin a1c (N total = 338848)" |
                                          Trait_label == "Glucose (N total = 419946)" |
                                          Trait_label == "High density lipoprotein cholesterol (N total = 404121)" |
                                          Trait_label == "Low density lipoprotein cholesterol (N total = 404741)" |
                                          Trait_label == "Diabetes / \"sugar\" (N cases = 80160, N controls = 235508)" |
                                          Trait_label == "High cholesterol (N cases = 176604, N controls = 139064)" |
                                          Trait_label == "Diabetes mellitus (N cases = 154958, N controls = 276347)" |
                                          Trait_label == "Diseases of esophagus (N cases = 189441, N controls = 223867)"|
                                          Trait_label == "Esophagitis, GERD and related diseases (N cases = 185368, N controls = 228046)" |
                                          Trait_label == "GERD (N cases = 175991, N controls = 236737)" |
                                          Trait_label == "Total cholesterol (N total = 397615)" |
                                          Trait_label == "Triglyceride (N total = 391626)")

for (i in seq(1, nrow(all_traits_sub), 16)){
  enrichment_plot(all_traits_sub[i:(i+15),], group="Category", xlim=c(-120,120))
}
```

# Interactive table of all traits and their enrichments
```{r}
write.csv(all_traits, "/dartfs/rc/lab/S/Szhao/katieh/organoid-rotation/outputs/MVP_traits_enrichment.csv")
datatable(all_traits)
```




