---
title: "UK Biobank Phenotypes"
author: "Katie Hooker"
date: "2025-01-15"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_knit$set(root.dir = "/dartfs/rc/lab/S/Szhao/katieh/organoid-rotation")

```


## Reading in the [phenotype manifest](https://pan.ukbb.broadinstitute.org/docs/per-phenotype-files)

```{r}
library(readxl)

phenoManifest <- suppressWarnings(read_excel("data/Pan-UK Biobank phenotype manifest.xlsx", sheet = "phenotype_manifest"))

h2Manifest <- suppressWarnings(read_excel("data/Pan-UK Biobank phenotype manifest.xlsx", sheet = "h2_manifest"))

```


## Restricting to full cohort size \>= 10,000

```{r}
library(dplyr)

TenK_pheno <- subset(phenoManifest, n_cases_full_cohort_both_sexes >= 10000)

```


## Restricting phenotypes by keyword(s)

```{r}
library(stringr)

# Searching for keywords
TenK_pheno_filtered <- TenK_pheno %>% filter(
  str_detect(category, "Biological samples") |
    str_detect(category, "Chapter IV Endocrine, nutritional and metabolic diseases") |
    str_detect(category, "Chapter XI Diseases of the digestive system") |
    str_detect(category, "R10-R19 Symptoms and signs involving the digestive system and abdomen") |
    category == "endocrine/metabolic" |
    category == "digestive" |
    category == "neoplasms" |
    category == "congenital anomalies"|
    str_detect(category, "D10-D36 Benign neoplasms") |
    str_detect(trait_efo_categories, "Digestive system") |
    str_detect(trait_efo_categories, "Lipid or lipoprotein measurement") |
    str_detect(trait_efo_categories, "Liver enzyme measurement") |
    str_detect(trait_efo_categories, "Metabolic disorder"))
    # str_detect(trait_efo_categories, "Cancer") |
    # str_detect(trait_efo_categories, "Other disease") |
    # str_detect(trait_efo_categories, "Other measurement") |
    # str_detect(trait_efo_categories, "Other trait"))

print(nrow(TenK_pheno_filtered))

```


```{r}
# Removing diseases of family members
TenK_pheno_filtered <- TenK_pheno_filtered %>% filter(!startsWith(description, "Illnesses of"))
print(nrow(TenK_pheno_filtered))

# Removing blood count assays
TenK_pheno_filtered <- TenK_pheno_filtered %>% filter(str_detect(category, "(?i)Blood count", negate=TRUE)) # (?i) specifies to ignore case
print(nrow(TenK_pheno_filtered))

# Removing abnormalities in urine
TenK_pheno_filtered <- TenK_pheno_filtered %>% filter(str_detect(description, "(?i)in urine", negate=TRUE))
print(nrow(TenK_pheno_filtered))

# Removing measures adjusted by medication
TenK_pheno_filtered <- TenK_pheno_filtered %>% filter(str_detect(description, "(?i)adjusted by medication", negate=TRUE))
print(nrow(TenK_pheno_filtered))

# Removing other non-digestive traits
TenK_pheno_filtered <- TenK_pheno_filtered %>% 
  filter(str_detect(description, "(?i)Breast", negate=TRUE) &
           str_detect(description, "(?i)skin", negate=TRUE) &
           str_detect(description, "(?i)uter", negate=TRUE))
print(nrow(TenK_pheno_filtered))

# Removing non-digestive specific descriptions
TenK_pheno_filtered <- TenK_pheno_filtered %>% 
  filter(description != "Cancer, suspected or other" &
  description != "Malignant neoplasm, other" &
  description != "Chemotherapy" &
  description != "Secondary malignant neoplasm")
print(nrow(TenK_pheno_filtered))

```

## Adding back in phenocodes for ICD10 traits

The phenocodes are lost in the read_excel process, but the ICD10 phenocodes are equal to the Letter + 2-digit number format of the description column.

```{r}
TenK_pheno_filtered <- TenK_pheno_filtered %>%
  mutate(phenocode = ifelse(trait_type == "icd10", 
                       str_sub(description, 1, 3), phenocode)) 
```

## Restricting to European $h^2 >= 0.1$

```{r}
EUR_h2 <- h2Manifest[h2Manifest$pop == "EUR",]
EUR_h2 <- EUR_h2 %>% select(trait_type, phenocode, pheno_sex, coding, modifier, pop,
                            estimates.ldsc.h2_observed)
EUR_h2$phenocode <- as.character(EUR_h2$phenocode)

TenK_pheno_filtered <- left_join(TenK_pheno_filtered, EUR_h2, by = c("trait_type","phenocode","pheno_sex","coding","modifier")) 

TenK_pheno_filtered <- TenK_pheno_filtered %>% subset(estimates.ldsc.h2_observed >= 0.1)
print(nrow(TenK_pheno_filtered))

```

## Removing duplicates across trait_types

```{r}
#TenK_pheno_filtered$description
#TenK_pheno_filtered$coding_description
```


