---
title: "Functional Enrichment Analysis Plots - UKBB"
author: "Katie Hooker"
date: "2025-03-03"
output: html_document
---


This script is for plotting the outputs of the functional enrichment analysis validation run on the 24 selected UKBB phenotypes.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggplot2))
library(stringr)
library(DT)

```

# Plotting function
```{r}
enrichment_plot <- function(data, group, xlim=NULL){
  
  group = sym(group)
  p <- ggplot(data, aes(x = Enrichment, y = !!group))+
    geom_point() +
    xlab("Enrichment") +
    geom_errorbarh(aes(xmin=Enrichment-CI_width, xmax=Enrichment+CI_width), height=.2) +
    facet_wrap(Trait_label~.,ncol = 1) +
    theme_bw()  +
    geom_vline(xintercept = 1,linetype="dotted", colour = "red") +
    theme(axis.ticks = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(colour = "black"),
      axis.text = element_text(size = 8, colour = "black"),
      axis.title = element_text(face="bold",size = 12),
      strip.text = element_text(face="bold",size = 10),
      panel.spacing.x = unit(0.6,units = "cm"),
      axis.title.y = element_blank(),
      legend.position = "none",
      plot.title = element_text(hjust = 0.5))
  
  if(!is.null(xlim)){
    p <- p + coord_cartesian(xlim = xlim)
  }
  print(p)

}
```

# Compiling all trait results
```{r}
output_path <- "/dartfs/rc/lab/S/Szhao/katieh/organoid-rotation/outputs/UKBB/results/"

# Reading in trait abbreviations and their corresponding trait names
pheno_list <- read.csv("/dartfs/rc/lab/S/Szhao/katieh/organoid-rotation/data/UKBB_pheno_list_validation.csv")

pheno_list$N_desc <- NA

for (trait in pheno_list$phenocode){
  pheno_list[pheno_list$phenocode == trait,]$N_desc <- paste0("N total = ", pheno_list[pheno_list$phenocode == trait,]$n_cases_full_cohort_both_sexes)
}

pheno_list <- pheno_list %>% mutate(Short_desc = paste0(description, " (", N_desc, ")"))
traits <- pheno_list$phenocode
traitslab <- pheno_list$Short_desc

all_traits <- NULL 
for (i in 1:length(traits)){
  efile1 <- read.table(paste0(output_path, sprintf("%s_enrichment.results", traits[i])),
                       header=T)
  enrich <- efile1[1:4,c(1,5,6,7)]
  enrich$CI_width <- 1.96*enrich$Enrichment_std_error
  enrich$Trait <- traits[i]
  enrich$Trait_label <- traitslab[i]

  if(is.null(all_traits)){
    all_traits <- enrich
  } else{
    all_traits <- rbind(all_traits, enrich)
  }
}
```

# Plot all traits, four at a time
```{r}
for (i in seq(1, nrow(all_traits), 16)){
  enrichment_plot(all_traits[i:(i+15),], group="Category", xlim=c(-120,120))
}
```

# Plot traits of interest
```{r}
all_traits_sub <- all_traits %>% subset(Trait_label == "Cholesterol (N total = 420607)" |
                                          Trait_label == "Glycated haemoglobin (HbA1c) (N total = 419434)" |
                                          Trait_label == "HDL cholesterol (N total = 385023)" |
                                          Trait_label == "LDL direct (N total = 419831)"  |
                                          Trait_label == "Triglycerides (N total = 420271)" |
                                          Trait_label == "Glucose (N total = 384760)")

for (i in seq(1, nrow(all_traits_sub), 12)){
  enrichment_plot(all_traits_sub[i:(i+11),], group="Category", xlim=c(-120,120))
}
```

# Interactive table of all traits and their enrichments
```{r}
datatable(all_traits)
```






